In [1]:
from pathlib import Path

import pandas as pd
import wbgapi as wb

## 1. World Bank country lookup table

In [2]:
world_bank_regions: pd.DataFrame = wb.economy.DataFrame()
world_bank_regions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 266 entries, ABW to ZWE
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         266 non-null    object
 1   aggregate    266 non-null    bool
 2   longitude    211 non-null    float64
 3   latitude     211 non-null    float64
 4   region       266 non-null    object
 5   adminregion  266 non-null    object
 6   lendingType  266 non-null    object
 7   incomeLevel  266 non-null    object
 8   capitalCity  266 non-null    object
dtypes: bool(1), float64(2), object(6)
memory usage: 19.0+ KB

In [ ]:
world_bank_regions

,name,aggregate,longitude,latitude,region,adminregion,lendingType,incomeLevel,capitalCity
id,,,,,,,,,
ABW,Aruba,False,-70.0167,12.51670,LCN,,LNX,HIC,Oranjestad
AFE,Africa Eastern and Southern,True,NaN,NaN,,,,,
AFG,Afghanistan,False,69.1761,34.52280,MEA,MNA,IDX,LIC,Kabul
AFW,Africa Western and Central,True,NaN,NaN,,,,,
AGO,Angola,False,13.2420,-8.81155,SSF,SSA,IBD,LMC,Luanda
...,...,...,...,...,...,...,...,...,...
XKX,Kosovo,False,20.9260,42.56500,ECS,ECA,IDX,UMC,Pristina
YEM,"Yemen, Rep.",False,44.2075,15.35200,MEA,MNA,IDX,LIC,Sana'a
ZAF,South Africa,False,28.1871,-25.74600,SSF,SSA,IBD,UMC,Pretoria
ZMB,Zambia,False,28.2937,-15.39820,SSF,SSA,IDX,LMC,Lusaka
ZWE,Zimbabwe,False,31.0672,-17.83120,SSF,SSA,IDB,LMC,Harare

In [ ]:
wb_regions_df = (
    world_bank_regions
    .reset_index()
    .rename(columns={'id': 'iso-alpha3_code'})
    .drop(columns=[
        'aggregate',
        'longitude',
        'latitude',
        'lendingType',
        'incomeLevel',
        'capitalCity'
    ])
    .replace({'': pd.NA})
)
wb_regions_df

    iso-alpha3_code                         name region adminregion
0               ABW                        Aruba    LCN        <NA>
1               AFE  Africa Eastern and Southern   <NA>        <NA>
2               AFG                  Afghanistan    MEA         MNA
3               AFW   Africa Western and Central   <NA>        <NA>
4               AGO                       Angola    SSF         SSA
..              ...                          ...    ...         ...
261             XKX                       Kosovo    ECS         ECA
262             YEM                  Yemen, Rep.    MEA         MNA
263             ZAF                 South Africa    SSF         SSA
264             ZMB                       Zambia    SSF         SSA
265             ZWE                     Zimbabwe    SSF         SSA

[266 rows x 4 columns]

In [5]:
wb_regions_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   iso-alpha3_code  266 non-null    object
 1   name             266 non-null    object
 2   region           217 non-null    object
 3   adminregion      129 non-null    object
dtypes: object(4)
memory usage: 8.4+ KB

## 2. UN M49 country lookup table

In [6]:
project_dir = Path.cwd().parent
common_table_dir = project_dir / 'data' / 'common-tables'
un_countries_path = common_table_dir / 'UNSD — Methodology.csv'

un_countries_df: pd.DataFrame = pd.read_csv(un_countries_path, sep=';')
original_un_countries_df = un_countries_df.copy(deep=True)

In [7]:
un_countries_df.head()

,Global Code,Global Name,Region Code,Region Name,Sub-region Code,Sub-region Name,Intermediate Region Code,Intermediate Region Name,Country or Area,M49 Code,ISO-alpha2 Code,ISO-alpha3 Code,Least Developed Countries (LDC),Land Locked Developing Countries (LLDC),Small Island Developing States (SIDS)
0,1,World,2.0,Africa,15.0,Northern Africa,NaN,NaN,Algeria,12,DZ,DZA,NaN,NaN,NaN
1,1,World,2.0,Africa,15.0,Northern Africa,NaN,NaN,Egypt,818,EG,EGY,NaN,NaN,NaN
2,1,World,2.0,Africa,15.0,Northern Africa,NaN,NaN,Libya,434,LY,LBY,NaN,NaN,NaN
3,1,World,2.0,Africa,15.0,Northern Africa,NaN,NaN,Morocco,504,MA,MAR,NaN,NaN,NaN
4,1,World,2.0,Africa,15.0,Northern Africa,NaN,NaN,Sudan,729,SD,SDN,x,NaN,NaN

In [8]:
un_countries_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 15 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Global Code                              248 non-null    int64
 1   Global Name                              248 non-null    object
 2   Region Code                              247 non-null    float64
 3   Region Name                              247 non-null    object
 4   Sub-region Code                          247 non-null    float64
 5   Sub-region Name                          247 non-null    object
 6   Intermediate Region Code                 105 non-null    float64
 7   Intermediate Region Name                 105 non-null    object
 8   Country or Area                          248 non-null    object
 9   M49 Code                                 248 non-null    int64
 10  ISO-alpha2 Code                          247 non-null    object
 11  ISO-alpha3 Code                          248 non-null    object
 12  Least Developed Countries (LDC)          44 non-null     object
 13  Land Locked Developing Countries (LLDC)  32 non-null     object
 14  Small Island Developing States (SIDS)    53 non-null     object
dtypes: float64(3), int64(2), object(10)
memory usage: 29.2+ KB

In [9]:
un_region_codes_df = (
    un_countries_df
    .filter(
        items=['M49 Code', 'ISO-alpha2 Code', 'ISO-alpha3 Code'],
        axis='columns'
    )
    .rename(columns={'M49 Code': 'm49_code',
                     'ISO-alpha2 Code': 'iso-alpha2_code',
                     'ISO-alpha3 Code': 'iso-alpha3_code'})
)
un_region_codes_df.head(3)

   m49_code iso-alpha2_code iso-alpha3_code
0        12              DZ             DZA
1       818              EG             EGY
2       434              LY             LBY

In [ ]:
un_levels: list[tuple] = [
    ('Global Code', 'Global Name'),
    ('Region Code', 'Region Name'),
    ('Sub-region Code', 'Sub-region Name'),
    ('Intermediate Region Code', 'Intermediate Region Name'),
    ('M49 Code', 'Country or Area'),
]

level_frames: list[pd.DataFrame] = []
for code_col, name_col in un_levels:
    temp = (
        un_countries_df
        .dropna(subset=[code_col])
        [[code_col, name_col]]  # Remove all cols except Code & Name
        .rename(columns={code_col: 'm49_code', name_col: 'm49_name'})
    )
    level_frames.append(temp)

# Construct country lookup table
all_regions_df = (
    pd
    .concat(level_frames, ignore_index=True)
    .drop_duplicates(subset=['m49_code', 'm49_name'])
    .sort_values(by='m49_code')
    .reset_index(drop=True)
    .convert_dtypes()
)

# Merge m49 codes with ISO-alpha codes & World Bank names
all_regions_df = all_regions_df.merge(un_region_codes_df, on='m49_code', how='left')
all_regions_df = (
    all_regions_df
    .merge(wb_regions_df, on='iso-alpha3_code', how='outer')
    .rename(columns={'name': 'world_bank_name'})
    .drop(columns=['region', 'adminregion'])
)

In [38]:
all_regions_df.columns

Index(['m49_code', 'm49_name', 'iso-alpha2_code', 'iso-alpha3_code',
       'world_bank_name'],
      dtype='object')

### Import StatCan regions from `StatCan-transformations.ipynb`

In [30]:
%store -r statcan_regions

# Convert `statcan_regions` to a dataframe
statcan_regions_df: pd.DataFrame = statcan_regions.rename('statcan_name').to_frame()
original_statcan_regions_df = statcan_regions_df.copy(deep=True)
statcan_regions_df.head()

    statcan_name
0    Afghanistan
1         Africa
2        Albania
3        Algeria
4  All countries

In [12]:
un_merged = statcan_regions_df.merge(
    all_regions_df,
    how='left',
    left_on='statcan_name',
    right_on='m49_name',
)
wb_merged = statcan_regions_df.merge(
    all_regions_df,
    how='left',
    left_on='statcan_name',
    right_on='world_bank_name',
)

# Coalesce: combine where `un_merge` is Null
statcan_merged = (
    un_merged
    .combine_first(wb_merged)
    .convert_dtypes()
)
statcan_merged

,statcan_name,m49_code,m49_name,iso-alpha2_code,iso-alpha3_code,world_bank_name
0,Afghanistan,4,Afghanistan,AF,AFG,Afghanistan
1,Africa,2,Africa,<NA>,<NA>,<NA>
2,Albania,8,Albania,AL,ALB,Albania
3,Algeria,12,Algeria,DZ,DZA,Algeria
4,All countries,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...
265,Yemen,887,Yemen,YE,YEM,"Yemen, Rep."
266,Yugoslavia,<NA>,<NA>,<NA>,<NA>,<NA>
267,Zaire,<NA>,<NA>,<NA>,<NA>,<NA>
268,Zambia,894,Zambia,ZM,ZMB,Zambia
269,Zimbabwe,716,Zimbabwe,ZW,ZWE,Zimbabwe

In [13]:
statcan_unmatched = (
    statcan_merged.loc[
        statcan_merged[['m49_name', 'world_bank_name']].isna().all(axis=1)
        & statcan_merged['statcan_name'].notna()
    ]
)
statcan_unmatched.head()

,statcan_name,m49_code,m49_name,iso-alpha2_code,iso-alpha3_code,world_bank_name
4,All countries,<NA>,<NA>,<NA>,<NA>,<NA>
15,Asia/Oceania,<NA>,<NA>,<NA>,<NA>,<NA>
40,Burma,<NA>,<NA>,<NA>,<NA>,<NA>
49,"Central America, South America, and Caribbean",<NA>,<NA>,<NA>,<NA>,<NA>
58,"Congo, Democratic Republic of the",<NA>,<NA>,<NA>,<NA>,<NA>

In [14]:
wb_names = set(all_regions_df['world_bank_name'].dropna())
un_names = set(all_regions_df['m49_name'].dropna())
statcan_unmatched_names = set(statcan_unmatched['statcan_name'].dropna())

to_be_matched = {
    'statcan_unmatched': sorted(list(statcan_unmatched_names)),
    'un_names': sorted(list(un_names)),
    'world_bank_names': sorted(list(wb_names))
}
to_be_matched

{'statcan_unmatched': ['All countries',
  'Asia/Oceania',
  'Burma',
  'Central America, South America, and Caribbean',
  'Congo, Democratic Republic of the',
  'Czechoslovakia',
  "Côte d'Ivoire",
  'Federated States of Micronesia',
  'German Democratic Republic (East)',
  'High Seas',
  'Hong Kong',
  'Iran',
  'Laos',
  'Macao',
  'Middle East',
  'Netherlands Antilles',
  'North Korea',
  'Oceania and Antarctica',
  'Other Africa',
  'Other Asia and Oceania',
  'Other Caribbean',
  'Other Europe',
  'Other South and Central America',
  'Pacific Islands',
  'Saint Martin (French part)',
  'South Korea',
  'South and Central America',
  'Syria',
  'Taiwan',
  'Tanzania, United Republic of',
  'Unallocated countries',
  'Union of Soviet Socialist Republics',
  'Unspecified',
  'Venezuela',
  'Wallis and Futuna',
  'Yugoslavia',
  'Zaire'],
 'un_names': ['Afghanistan',
  'Africa',
  'Albania',
  'Algeria',
  'American Samoa',
  'Americas',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Asia',
  'Australia',
  'Australia and New Zealand',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia (Plurinational State of)',
  'Bonaire, Sint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'British Virgin Islands',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Caribbean',
  'Cayman Islands',
  'Central African Republic',
  'Central America',
  'Central Asia',
  'Chad',
  'Chile',
  'China',
  'China, Hong Kong Special Administrative Region',
  'China, Macao Special Administrative Region',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curaçao',
  'Cyprus',
  'Czechia',
  'Côte d’Ivoire',
  "Democratic People's Republic of Korea",
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Eastern Africa',
  'Eastern Asia',
  'Eastern Europe',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Europe',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People's Democratic Republic",
  'Latin America and the Caribbean',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Melanesia',
  'Mexico',
  'Micronesia',
  'Micronesia (Federated States of)',
  'Middle Africa',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands (Kingdom of the)',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'North Macedonia',
  'Northern Africa',
  'Northern America',
  'Northern Europe',
  'Northern Mariana Islands',
  'Norway',
  'Oceania',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Polynesia',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of Korea',
  'Republic of Moldova',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Réunion',
  'Saint Barthélemy',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (French Part)',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South America',
  'South Georgia and the South Sandwich Islands',
  'South Sudan',
  'South-eastern Asia',
  'Southern Africa',
  'Southern Asia',
  'Southern Europe',
  'Spain',
  'Sri Lanka',
  'State of Palestine',
  'Sub-Saharan Africa',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen Islands',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Tajikistan',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Türkiye',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom of Great Britain and Northern Ireland',
  'United Republic of Tanzania',
  'United States Minor Outlying Islands',
  'United States Virgin Islands',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela (Bolivarian Republic of)',
  'Viet Nam',
  'Wallis and Futuna Islands',
  'Western Africa',
  'Western Asia',
  'Western Europe',
  'Western Sahara',
  'World',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Åland Islands'],
 'world_bank_names': ['Afghanistan',
  'Africa Eastern and Southern',
  'Africa Western and Central',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Arab World',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas, The',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Virgin Islands',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Caribbean small states',
  'Cayman Islands',
  'Central African Republic',
  'Central Europe and the Baltics',
  'Chad',
  'Channel Islands',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo, Dem. Rep.',
  'Congo, Rep.',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cuba',
  'Curacao',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Early-demographic dividend',
  'East Asia & Pacific',
  'East Asia & Pacific (IDA & IBRD countries)',
  'East Asia & Pacific (excluding high income)',
  'Ecuador',
  'Egypt, Arab Rep.',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Euro area',
  'Europe & Central Asia',
  'Europe & Central Asia (IDA & IBRD countries)',
  'Europe & Central Asia (excluding high income)',
  'European Union',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'Fragile and conflict affected situations',
  'France',
  'French Polynesia',
  'Gabon',
  'Gambia, The',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guam',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heavily indebted poor countries (HIPC)',
  'High income',
  'Honduras',
  'Hong Kong SAR, China',
  'Hungary',
  'IBRD only',
  'IDA & IBRD total',
  'IDA blend',
  'IDA only',
  'IDA total',
  'Iceland',
  'India',
  'Indonesia',
  'Iran, Islamic Rep.',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  "Korea, Dem. People's Rep.",
  'Korea, Rep.',
  'Kosovo',
  'Kuwait',
  'Kyrgyz Republic',
  'Lao PDR',
  'Late-demographic dividend',
  'Latin America & Caribbean',
  'Latin America & Caribbean (excluding high income)',
  'Latin America & the Caribbean (IDA & IBRD countries)',
  'Latvia',
  'Least developed countries: UN classification',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Low & middle income',
  'Low income',
  'Lower middle income',
  'Luxembourg',
  'Macao SAR, China',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia, Fed. Sts.',
  'Middle East, North Africa, Afghanistan & Pakistan',
  'Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)',
  'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)',
  'Middle income',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North America',
  'North Macedonia',
  'Northern Mariana Islands',
  'Norway',
  'Not classified',
  'OECD members',
  'Oman',
  'Other small states',
  'Pacific island small states',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Post-demographic dividend',
  'Pre-demographic dividend',
  'Puerto Rico (US)',
  'Qatar',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovak Republic',
  'Slovenia',
  'Small states',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Asia',
  'South Asia (IDA & IBRD)',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'St. Kitts and Nevis',
  'St. Lucia',
  'St. Martin (French part)',
  'St. Vincent and the Grenadines',
  'Sub-Saharan Africa',
  'Sub-Saharan Africa (IDA & IBRD countries)',
  'Sub-Saharan Africa (excluding high income)',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkiye',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Upper middle income',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela, RB',
  'Viet Nam',
  'Virgin Islands (U.S.)',
  'West Bank and Gaza',
  'World',
  'Yemen, Rep.',
  'Zambia',
  'Zimbabwe']}

In [ ]:
# Matches made by ChatGPT o3, then manually reviewed
# Ambiguous matches moved to 'possible matches'
matched_by_ai = {
    "matches": [
        { "statcan": "All countries", "un": "World", "world_bank": "World" },
        { "statcan": "Burma", "un": "Myanmar", "world_bank": "Myanmar" },
        { "statcan": "Central America, South America, and Caribbean", "un": "Latin America and the Caribbean", "world_bank": "Latin America & Caribbean" },
        { "statcan": "Congo, Democratic Republic of the", "un": "Democratic Republic of the Congo", "world_bank": "Congo, Dem. Rep." },
        { "statcan": "Côte d'Ivoire", "un": "Côte d’Ivoire", "world_bank": "Cote d'Ivoire" },
        { "statcan": "Federated States of Micronesia", "un": "Micronesia (Federated States of)", "world_bank": "Micronesia, Fed. Sts." },
        { "statcan": "Hong Kong", "un": "China, Hong Kong Special Administrative Region", "world_bank": "Hong Kong SAR, China" },
        { "statcan": "Iran", "un": "Iran (Islamic Republic of)", "world_bank": "Iran, Islamic Rep." },
        { "statcan": "Laos", "un": "Lao People's Democratic Republic", "world_bank": "Lao PDR" },
        { "statcan": "Macao", "un": "China, Macao Special Administrative Region", "world_bank": "Macao SAR, China" },
        { "statcan": "Netherlands Antilles", "un": "Curaçao", "world_bank": "Curacao" },
        { "statcan": "North Korea", "un": "Democratic People's Republic of Korea", "world_bank": "Korea, Dem. People's Rep." },
        { "statcan": "Saint Martin (French part)", "un": "Saint Martin (French Part)", "world_bank": "St. Martin (French part)" },
        { "statcan": "South Korea", "un": "Republic of Korea", "world_bank": "Korea, Rep." },
        { "statcan": "Syria", "un": "Syrian Arab Republic", "world_bank": "Syrian Arab Republic" },
        { "statcan": "Tanzania, United Republic of", "un": "United Republic of Tanzania", "world_bank": "Tanzania" },
        { "statcan": "Venezuela", "un": "Venezuela (Bolivarian Republic of)", "world_bank": "Venezuela, RB" },
        { "statcan": "Wallis and Futuna", "un": "Wallis and Futuna Islands" },
        { "statcan": "Zair", "un": "Democratic Republic of the Congo", "world_bank": "Congo, Dem. Rep." },
    ],
    "possible_matches": [
        { "statcan": "Middle East", "un": "Western Asia", "world_bank": "Middle East, North Africa, Afghanistan & Pakistan" },
        { "statcan": "Pacific Islands", "un": "Oceania", "world_bank": "Pacific island small states" },
        { "statcan": "South and Central America", "un": "South America", "world_bank": "Latin America & Caribbean" },
        { "statcan": "Other Caribbean", "un": "Caribbean", "world_bank": "Caribbean small states" },
        { "statcan": "Other Europe", "un": "Europe", "world_bank": "Europe & Central Asia" },
        { "statcan": "Other South and Central America", "un": "South America", "world_bank": "Latin America & Caribbean" }
    ],
    "statcan_only": [
        "Asia/Oceania",
        "Czechoslovakia",
        "German Democratic Republic (East)",
        "High Seas",
        "Oceania and Antarctica",
        "Other Africa",
        "Other Asia and Oceania",
        "Unallocated countries",
        "Union of Soviet Socialist Republics",
        "Unspecified",
        "Taiwan",
        "Yugoslavia"
    ]
}

# Create df of matches
un_matches_by_ai = []
statcan_matched_by_ai = []
for match in matched_by_ai['matches']:
    for key, value in match.items():
        if key == 'statcan':
            statcan_matched_by_ai.append(value)
        elif key == 'un':
            un_matches_by_ai.append(value)
  
matched_by_ai_df = pd.DataFrame({'statcan_name': statcan_matched_by_ai,
                                 'm49_name': un_matches_by_ai})

# Create df of StatCan-exclusive regions
statcan_exclusive = []
for possible_match in matched_by_ai['possible_matches']:
    for key, value in possible_match.items():
        if key == 'statcan':
            statcan_exclusive.append(value)

statcan_exclusive_df = pd.DataFrame({'statcan_name': statcan_exclusive})

In [43]:
# statcan_matched_names = list(
#     set(statcan_regions_df['statcan_name'].to_list())
#     - set(statcan_matched_by_ai)
# )
# statcan_matched_df = pd.DataFrame({'statcan_name': statcan_matched_names})

KeyError: "None of ['m49_name'] are in the columns"

In [ ]:
# # Insert surrogate key once all transformations are complete
# all_regions_df.insert(0, 'region_id', all_regions_df.index+1)

# # Finally, reorder columns to final positions
# all_codes_df_col_order = [
#     'region_id',
#     'iso-alpha3_code',
#     'iso-alpha2_code',
#     'm49_code',
#     'm49_name',
#     'world_bank_name',
#     'statcan_name
# ]
# all_regions_df = all_regions_df[all_codes_df_col_order]

# all_regions_df.head()

### Aside: UN and World Bank have mutually exclusive ISO country codes

In [136]:
un_exclusive_iso_codes = (
    set(un_region_codes_df['iso-alpha3_code']) - set(wb_regions_df['iso-alpha3_code'])
)
wb_exclusive_iso_codes = (
    set(wb_regions_df['iso-alpha3_code']) - set(un_region_codes_df['iso-alpha3_code'])
)

exclusive_iso_codes = {
    'code_type': 'iso-alpha3_code',
    'wb_exclusive_codes': sorted(list(wb_exclusive_iso_codes)),
    'un_exclusive_codes': sorted(list(un_exclusive_iso_codes))
}

print(f'UN-exclusive ISO-Alpha 3 codes: {len(un_exclusive_iso_codes)}')
print(f'World Bank-exclusive ISO-Alpha 3 codes: {len(wb_exclusive_iso_codes)}')

UN-exclusive ISO-Alpha 3 codes: 33
World Bank-exclusive ISO-Alpha 3 codes: 51

In [ ]:


print(f'    World Bank name count: {len(wb_names)}\n'
      f'United Nations name count: {len(un_names)}')

wb_exclusive_names = wb_names - un_names
un_exclusive_names = un_names - wb_names

exclusive_names = {
    'wb_exclusive_names': sorted(list(wb_exclusive_names)),
    'un_exclusive_names': sorted(list(un_exclusive_names))
}
exclusive_names

    World Bank name count: 266
United Nations name count: 278
World Bank exclusive names:
    Heavily indebted poor countries (HIPC)
    Korea, Rep.
    IDA total
    Virgin Islands (U.S.)
    Kyrgyz Republic
    IBRD only
    Netherlands
    Macao SAR, China
    Curacao
    OECD members
    St. Kitts and Nevis
    Low & middle income
    Moldova
    North America
    Africa Eastern and Southern
    Pacific island small states
    Cote d'Ivoire
    Slovak Republic
    South Asia
    Lower middle income
    Pre-demographic dividend
    Middle income
    European Union
    Middle East, North Africa, Afghanistan & Pakistan (excluding high income)
    West Bank and Gaza
    United Kingdom
    Caribbean small states
    Early-demographic dividend
    East Asia & Pacific
    St. Vincent and the Grenadines
    Gambia, The
    Lao PDR
    Africa Western and Central
    Congo, Rep.
    Upper middle income
    St. Martin (French part)
    Channel Islands
    Central Europe and the Baltics
    Fragile and conflict affected situations
    Egypt, Arab Rep.
    Tanzania
    Middle East, North Africa, Afghanistan & Pakistan
    Small states
    Turkiye
    Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)
    Sub-Saharan Africa (IDA & IBRD countries)
    Latin America & the Caribbean (IDA & IBRD countries)
    Arab World
    Sub-Saharan Africa (excluding high income)
    Kosovo
    Micronesia, Fed. Sts.
    Late-demographic dividend
    Euro area
    Other small states
    Yemen, Rep.
    Bahamas, The
    IDA blend
    Iran, Islamic Rep.
    High income
    East Asia & Pacific (IDA & IBRD countries)
    IDA & IBRD total
    Europe & Central Asia (IDA & IBRD countries)
    Hong Kong SAR, China
    St. Lucia
    Venezuela, RB
    United States
    Post-demographic dividend
    Bolivia
    Europe & Central Asia
    Latin America & Caribbean (excluding high income)
    East Asia & Pacific (excluding high income)
    Latin America & Caribbean
    Korea, Dem. People's Rep.
    South Asia (IDA & IBRD)
    Low income
    Puerto Rico (US)
    Europe & Central Asia (excluding high income)
    IDA only
    Not classified
    Congo, Dem. Rep.
    Least developed countries: UN classification

============================

United Nations exclusive names:
    Micronesia (Federated States of)
    Tokelau
    Polynesia
    Northern Europe
    Réunion
    Venezuela (Bolivarian Republic of)
    Niue
    Wallis and Futuna Islands
    Western Africa
    Norfolk Island
    Micronesia
    Holy See
    Eastern Europe
    Saint Helena
    United States Minor Outlying Islands
    Svalbard and Jan Mayen Islands
    Australia and New Zealand
    Republic of Moldova
    Côte d’Ivoire
    China, Macao Special Administrative Region
    Iran (Islamic Republic of)
    Saint Martin (French Part)
    Europe
    Lao People's Democratic Republic
    United Republic of Tanzania
    Heard Island and McDonald Islands
    Gambia
    Åland Islands
    Caribbean
    Egypt
    Saint Kitts and Nevis
    Asia
    Kyrgyzstan
    Congo
    Western Europe
    Eastern Africa
    South Georgia and the South Sandwich Islands
    Türkiye
    Southern Asia
    Netherlands (Kingdom of the)
    Puerto Rico
    United States Virgin Islands
    Pitcairn
    Africa
    Antarctica
    Montserrat
    Saint Lucia
    British Indian Ocean Territory
    French Guiana
    Anguilla
    Falkland Islands (Malvinas)
    Cook Islands
    Southern Africa
    Southern Europe
    Yemen
    Western Sahara
    Guernsey
    Eastern Asia
    Americas
    Saint Barthélemy
    South America
    Democratic Republic of the Congo
    United States of America
    Northern America
    Bouvet Island
    Melanesia
    Central Asia
    Bolivia (Plurinational State of)
    Saint Pierre and Miquelon
    Saint Vincent and the Grenadines
    Oceania
    Cocos (Keeling) Islands
    French Southern Territories
    Middle Africa
    Guadeloupe
    Slovakia
    Curaçao
    Jersey
    China, Hong Kong Special Administrative Region
    South-eastern Asia
    Bahamas
    Mayotte
    Bonaire, Sint Eustatius and Saba
    Latin America and the Caribbean
    Martinique
    Democratic People's Republic of Korea
    Christmas Island
    United Kingdom of Great Britain and Northern Ireland
    Western Asia
    Northern Africa
    Central America
    Republic of Korea
    State of Palestine